// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XeroProducts.Data.Context;
using XeroProducts.Data.Models;

namespace XeroProducts.API.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20201125070735_InitialCreateSchema")]
    partial class InitialCreateSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("XeroProducts.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(17)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("XeroProducts.Models.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(23)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(9)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("ProductOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
